baseURL = 'https://blog.ashishghimire.com'
languageCode = 'en-us'

title = 'Ashish Blog'
theme = 'hugo-theme-puppet'

paginate = 3

enableInlineShortcodes = true
enableEmoji = true

googleAnalytics = "G-2RHJH43BKX"

[outputs]
home = ["HTML", "JSON", "RSS"]

[taxonomies]
category = "categories"
tag = "tags"

[markup]
[markup.highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark.renderer]
unsafe = true

# menu

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 10
[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20
[[menu.main]]
identifier = "notes"
name = "My Notes"
url = "https://notes.ashishghimire.com/"
weight = 50
[[menu.main]]
identifier = "dashboard"
name = "About"
url = "https://ashishghimire.com/"
weight = 100


[params]
author = "Ashish"
description = "A place where I pour my thoughts."
keywords = "blog, personal"
img_home = "img/cover.jpg"
img_404 = "img/404-bg.jpg"

useFaviconGenerator = true

[params.sidebar]
enable = true
gravatarEmail = ""
# Overwritten by your gravatar image if `gravatarEmail` is filled
avatar = "img/logoDark.png"
bio = "a personal website"

[params.social]
twitter = "aacsghimire"
# facebook = "johndoe"
# zhihu = "johndoe"
# weibo = "johndoe"
# github = "johndoe"
# gitlab = "johndoe"
# linkedin = "johndoe"
rss = true
[params.social.mastodon]
weight = 56
icon = "fab fa-mastodon"
format = "https://techhub.social/"
id = "aacsghimire"
url = "https://techhub.social/@aacsghimire"

[[params.friends]]
name = "Ayur Blogs"
url = "https://ayurblogs.com"

[params.giscus]
enable = true
repo = "aacsghimire/blogashish"
repo_id = "R_kgDOI21PBA"
category = "Comment"
data-mapping = "title"
category_id = "DIC_kwDOI21PBM4CUDKI"
input_position = "top"
theme = "light_tritanopia"
lang = "en"
data-input-position = "top"